name: echosegmentation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.13
  - ipython=8.6.0
  - ipykernel=6.17.1
  - ipywidgets=7.6.5
  - matplotlib=3.5.3
  - numpy=1.23.3
  - pandas=1.4.4
  - pip=22.2.2
  - scikit-learn=1.1.3
  - tqdm=4.64.1
  - h5py=3.7.0
  - pip:
    - light-the-torch==0.7.1
    - opencv-python==4.7.0.68
    - tensorboard==2.11.0